# DO-NOT-EDIT: Generated by github:vic/flake-file.
# To re-generate use: nix-shell . -A flake-file.sh --run write-inputs
{
  flake-file.url = "github:vic/flake-file";
  flake-parts = {
    inputs.nixpkgs-lib.follows = "nixpkgs-lib";
    url = "github:hercules-ci/flake-parts";
  };
  helium = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:AlvaroParker/helium-nix";
  };
  home-manager = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/home-manager";
  };
  import-tree.url = "github:vic/import-tree";
  niri = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:sodiboo/niri-flake";
  };
  nix-auto-follow = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:fzakaria/nix-auto-follow";
  };
  nixpkgs.url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz";
  nixpkgs-lib.follows = "nixpkgs";
  nixvim = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/nixvim";
  };
  stylix = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/stylix";
  };
}
